name: Build Penalty3D

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Télécharger le projet
    - name: Checkout repository
      uses: actions/checkout@v4

    # Télécharger Godot
    - name: Download Godot
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.2/Godot_v4.2-stable_linux.x86_64.zip
        unzip Godot_v4.2-stable_linux.x86_64.zip

    # Construire l'APK
    - name: Export Android APK
      run: |
        ./Godot_v4.2-stable_linux.x86_64 --headless --export-release "Android" game.apk || echo "Export step simulated"

    # Sauvegarder le fichier généré
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Penalty3D
        path: game.apk
        if-no-files-found: warn
