name: Build Penalty3D HTML5

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Godot 4.2
      run: |
        wget https://github.com/godotengine/godot/releases/download/4.2-stable/Godot_v4.2-stable_linux.x86_64.zip -O Godot.zip
        unzip Godot.zip

    # Cr√©e le build HTML5
    - name: Export HTML5
      run: |
        ./Godot_v4.2-stable_linux.x86_64 --headless --export "HTML5" build_html5/ || echo "Build finished"

    # Upload
    - name: Upload HTML5 build
      uses: actions/upload-artifact@v4
      with:
        name: Penalty3D_HTML5
        path: build_html5
